# If we're running in test mode.
# Override this from the command line with --config test=1
test: false

# Whether to display progress bars for certain rules
# Output can get screwed up if there are other running rules also printing to stdout
show_progress: false

# Number of simultaneous downloads for each genome download rule
dl_nworkers: 6

# Download source data to $REPO_ROOT/resources instead of $WORKDIR/resources.
# This avoids having to re-download all source data when running in a different working directory.
# Disable if testing download rules.
dl_to_src_dir: true

# Use HTTP protocol to access NCBI FTP server files instead of FTP (have had issues on some networks)
ncbi_use_http: false

# Truncate all genome sets to this size in test mode
test_genome_cap: 20


# Standard parameters for GAMBIT command line
gambit:
  k: 11
  prefix: ATGAC


# Parameters for FastANI
fastani:
  k: 16  # Default
  fraglen: 3000  # Default
  # Chunk queries so output matrices are no bigger than this
  chunk_size: 5000


# URLs for downloading source files
src_data:
  gambit_db:
    genomes: "hesslab-gambit-public/databases/refseq-curated/1.0-beta/gambit-genomes-1.0b1-210719.db"
    signatures: "hesslab-gambit-public/databases/refseq-curated/1.0-beta/gambit-signatures-1.0b1-210719.h5"

  genome_sets:
    set3: "hesslab-gambit-public/genomes/set3/fasta/"
    set4: "hesslab-gambit-public/genomes/set4/fasta/"
    set5: "hesslab-gambit-public/genomes/set5/fasta.tar.gz"
    set3_fastq: "hesslab-gambit-public/genomes/set3/fastq/"


# Values to use for parameter space exploration (figure 2 and supplemental figure 1)
gambit_param_space:
  k: [7, 9, 11, 13, 15, 17]
  prefix_len: [4, 5, 6, 7]
  base_prefix:
    # Standard ATGAC plus two random nucleotides:
    - ATGACTG
    # Remaining are randomly generated:
    - ATCATTT
    - TCTCGAT
    - GAAAGCG
    - TTGACCC
    - CACATAT
    - CGTTAGT
    - ACTCTTG


figure_3:
  # Genomes to plot
  genomes:
    # Chosen to be around the median precision/recall of all genomes
    - "16AC1611141-CAP"
    - "18AC0012153M"
    - "18AC0017658"
    - "19AC0011211-2"
    - "17AC0006312"


figure_4:
  subplots:
    a:
      # Klebsiella pneumoniae vs K. variicola
      in_taxon: 801
      out_taxa: [803]
    b:
      # Neisseria gonorrhoeae vs N. meningitidis
      in_taxon: 869
      out_taxa: [870]


figure_5:
  subplots:
    # Shigella boydii vs S. dysenteriae
    a:
      in_taxon: 1909
      out_taxa: [1910]
      bin_width: 0.01
    # Pseudomonas amygdali vs. P. syringae and P. savastanoi
    b:
      in_taxon: 655
      out_taxa: [634, 647]
      bin_width: 0.02
